### ISSUE TITLE
"List All Transactions" documentation has incomplete `filters`

### ISSUE THREAD

**Issue by gugahoi** [basiqio/api-ref#127]
When reading the documentation, the ["List all transactions"](https://api.basiq.io/reference/gettransactions) page mentions a `filter` query parameter with some dropdown options (see image below):

![image](https://user-images.githubusercontent.com/355877/212573326-263c583d-0008-4406-8b10-b0b5db02d773.png)

These options are not the correct filters, as they are missing the operators needed to utilize them (at least that's how it used to work in v2.0). Consequently, the generated SDKs are also missing the correct options for the filters which makes it a pretty bad developer experience.

Are you planning to rectify this in the docs? To note, the example requests for all languages and formats consequently is also incorrect.

**Comment by ashmanmalik** [comment]
Thanks @gugahoi for raising this bug. I'll be going to rectify this in the docs. I will update you here once this is in process. 

### Internal Reference 

DEVX-245

**Comment by ashmanmalik** [comment]
Hey @gugahoi I have rectified this bug, thanks again for raising this with us. I have removed the list and added a string filter. I hope this helps. 

<img width="1384" alt="Screenshot 2023-01-24 at 10 27 04 am" src="https://user-images.githubusercontent.com/9534690/214218490-18cc79b8-1f90-4dee-9a0c-c4313b1ccc26.png">
