### ISSUE TITLE
core api: spec validation issue

### ISSUE THREAD

**Issue by bcmedeiros** [basiqio/api-ref#259]
I'm trying to use `org.openapitools` codegen to process the core API, currently getting the following error:
```
org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 31
Errors: 
	-attribute components.schemas.EventTypes.items is missing
Warnings: 
	-attribute components.schemas.EventTypes.items is missing
```

Is that a false alarm, or is it really an issue in the spec?

**Comment by basiq-ash** [comment]
HI @bcmedeiros Let me have a look into this one and will get back to you.

**Comment by basiq-ash** [comment]
Hey @bcmedeiros Thanks for raising this one, I have checked this error and identified as bug, I have resolved this now and test it as well. Awaiting for PR review and once it's done, you can re-generate and confirm here.

**Comment by basiq-brad** [comment]
Thanks @bcmedeiros This has now be merged.
