### ISSUE TITLE
List webhooks returns data as array but type is object in api docs

### ISSUE THREAD

**Issue by mailaneel** [basiqio/api-ref#368]
Endpoint: https://au-api.basiq.io/notifications/webhooks
Docs: https://api.basiq.io/reference/listappwebhooks
OpenApi: https://github.com/basiqio/api-ref/blob/287d93d50496a13fef8e6e36b413a3c616a7040e/webhooks.yml#L164

**Actual response from api**

```json
{
  "data": {
    "type": "list",
    "count": 1,
    "size": 500,
    "data": [
      {
        "type": "webhook",
        "id": "xxx",
        "name": "",
        "description": "",
        "url": "https://example.com",
        "status": "active",
        "subscribedEvents": [
          "connection.created",
          "connection.deleted",
          "consent.created",
          "consent.expired",
          "consent.reminder",
          "consent.revoked",
          "consent.updated",
          "consent.warning",
          "user.created",
          "user.updated",
          "user.deleted"
        ],
        "links": { "self": "https://au-api.basiq.io/notifications/webhooks/xxx" }
      }
    ],
    "links": { "self": "https://au-api.basiq.io/notifications/webhooks" }
  }
}

```

**Comment by basiq-ash** [comment]
Thanks for raising this @mailaneel we'll check and get back to you.

**Comment by basiq-ash** [comment]
Hi @mailaneel Thanks for raising this bug in the docs, I have updated our api ref [here](https://github.com/basiqio/api-ref/blob/f2de50c44352952ef25b5a52d1a6c64789a16959/webhooks.yml#L1161). 

You can also confirm it on our API docs: https://api.basiq.io/reference/listappwebhooks
Attaching a screenshot as well. 

<img width="1369" alt="WebhooksDocs" src="https://github.com/basiqio/api-ref/assets/102712545/c4454608-e431-4f4c-b1ed-8c970ec58fc4">

**Comment by mailaneel** [comment]
thank you
