### ISSUE TITLE
"none" option missing for enriched category's matchType

### ISSUE THREAD

**Issue by mailaneel** [basiqio/api-ref#372]
**Enriched response**
![Screenshot 2024-04-11 at 5 12 39 pm](https://github.com/basiqio/api-ref/assets/129355/e32d2ae0-5cf8-4e90-95d3-fd48fbd6ca0c)

**Current docs**
![Screenshot 2024-04-11 at 5 14 32 pm](https://github.com/basiqio/api-ref/assets/129355/fe42f8c7-4ec8-4e9b-bede-b04ee1c2052d)

**Comment by basiq-ash** [comment]
Thanks @mailaneel for raising this. We return `none` value, when we are unable to classify a business classification code. I will update the enums shortly.
