### ISSUE TITLE
Jobs type mismatch in docs and api response

### ISSUE THREAD

**Issue by mailaneel** [basiqio/api-ref#377]
Jobs response from api returns institution but docs have partnerId and applicationId.

![Screenshot 2024-04-23 at 10 28 34 am](https://github.com/basiqio/api-ref/assets/129355/0d68cfbe-c056-4cdc-b97d-9772906c3471)

![Screenshot 2024-04-23 at 10 44 17 am](https://github.com/basiqio/api-ref/assets/129355/69e0fd86-b533-4eec-8e71-3d7d27580758)

**Comment by mailaneel** [comment]
Also I see status parameter is not returned in api response but mentioned in docs

**Comment by basiq-ash** [comment]
Hey @mailaneel the Job endpoint has multiple responses in it, we have payments jobs that returns `partnerId`, `applicationId` and `status` which are optional in data type jobs. 
  
![Screenshot 2024-04-23 at 11 12 36 AM](https://github.com/basiqio/api-ref/assets/102712545/6fef7934-18d5-4933-a4e4-6530398c3c11)

Moreover, the institution is returned in a different endpoint. Can you please confirm what endpoint you are calling? 

![Screenshot 2024-04-23 at 11 15 54 AM](https://github.com/basiqio/api-ref/assets/102712545/ff2cde61-3457-418e-9f09-c90dccfdf4b0)

**Comment by mailaneel** [comment]
I was using Get user jobs endpoint and thought Retrieve job also has same structure

**Comment by basiq-ash** [comment]
Thanks @mailaneel the structure is similar with some optional attributes. Do you want me to close this issue?

**Comment by mailaneel** [comment]
Okay thank you for quick response, much appreciated
