### ISSUE TITLE
Accounts depositRates.tiers & lendingRates.tiers mismatch in docs vs api response

### ISSUE THREAD

**Issue by peterjskaltsis** [basiqio/api-ref#388]
👋  

Hoping you can confirm if this is something to fix on the docs.

Accounts response from the Basiq API returns account with `lendingRates.tiers` & `depositRates.tiers` as arrays, but docs have tiers returning an object.

**Basiq Accounts Response**
 <img width="564" alt="Screenshot 2024-05-10 at 9 54 57 AM" src="https://github.com/basiqio/api-ref/assets/4243672/7deaf7a2-b1bd-4a0f-9867-5f3aab6c78d1">

**Docs**
<img width="564" alt="Screenshot 2024-05-10 at 9 57 48 AM" src="https://github.com/basiqio/api-ref/assets/4243672/a4ec4ac2-1d58-4b84-868d-083d6bafb690">

This is causing a type issue on our side.

**Comment by peterjskaltsis** [comment]
Noticing `List accounts` has return type depositRates.tiers as **Array**:

<img width="951" alt="Screenshot 2024-05-10 at 10 07 12 AM" src="https://github.com/basiqio/api-ref/assets/4243672/9527c4ef-9a91-46a8-a2ce-3b56955d5932">

Whereas `Retrieve account` has return type as **Object**:

<img width="951" alt="Screenshot 2024-05-10 at 10 05 27 AM" src="https://github.com/basiqio/api-ref/assets/4243672/c80b3357-8a3c-4c84-bbf5-6b7cee78cc08">

**Comment by basiq-ash** [comment]
@peterjskaltsis Thanks for highlighting this through. We will check on our end and will get back to you.

**Comment by basiq-ash** [comment]
Thanks for raising this one @peterjskaltsis I will rectify this one soon.

**Comment by basiq-ash** [comment]
Opened PR #389

**Comment by basiq-ash** [comment]
@peterjskaltsis here's the rectified version. Thanks again for raising this one 👍 

![Screenshot 2024-05-10 at 11 08 13 AM](https://github.com/basiqio/api-ref/assets/102712545/92acbe49-8cd8-4126-bec5-330b1a1f1b99)

**Comment by peterjskaltsis** [comment]
Much appreciated, thank you!

Just one more clarification, is discounts also meant to be an **Array**? It's currently an Object in docs but is described as a list?

<img width="617" alt="Screenshot 2024-05-10 at 11 32 14 AM" src="https://github.com/basiqio/api-ref/assets/4243672/1d25bf24-4dea-4c4b-873c-9e1c9270b843">

**Comment by basiq-ash** [comment]
@peterjskaltsis Yep you are right, that one is also rectified on #390

**Comment by peterjskaltsis** [comment]
Amazing thank you for the prompt response 🙏
